CREATE TABLE APP.USERS
(
  id            INT                NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  username      VARCHAR(50) UNIQUE NOT NULL,
  firstname     VARCHAR(50),
  lastname      VARCHAR(50),
  password      VARCHAR(32),
  magnetic_card VARCHAR(32) UNIQUE,
  is_admin      CHAR(1)                     DEFAULT 'N',
  CONSTRAINT USERS_key PRIMARY KEY (id)
);

CREATE TABLE APP.COCKTAIL_GROUPS
(
  id   INT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  name VARCHAR(50) UNIQUE,
  CONSTRAINT COCKTAIL_GROUPS_key PRIMARY KEY (id)
);

CREATE TABLE APP.COCKTAILS
(
  id       INT                NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  name     VARCHAR(50) UNIQUE NOT NULL,
  group_id INT                NOT NULL,
  CONSTRAINT COCKTAILS_key PRIMARY KEY (id),
  CONSTRAINT COCKTAILS_COCKTAIL_GROUPS_ID_fk
  FOREIGN KEY (group_id) REFERENCES COCKTAIL_GROUPS (id)
    ON DELETE CASCADE
);

CREATE TABLE APP.INGREDIENTS
(
  id       INT                NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  name     VARCHAR(50) UNIQUE NOT NULL,
  velocity FLOAT(5)           NOT NULL,
  CONSTRAINT INGREDIENTS_key PRIMARY KEY (id)
);

CREATE TABLE APP.COCKTAILS_INGREDIENTS
(
  id            INT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  cocktail_id   INT NOT NULL,
  ingredient_id INT NOT NULL,
  millilitres   INT NOT NULL,
  CONSTRAINT COCKTAILS_INGREDIENTS_key PRIMARY KEY (id),
  CONSTRAINT COCKTAILS_INGREDIENTS_COCKTAIL_fk
  FOREIGN KEY (cocktail_id) REFERENCES COCKTAILS (id)
    ON DELETE CASCADE,
  CONSTRAINT COCKTAILS_INGREDIENTS_INGREDIENTS_fk
  FOREIGN KEY (ingredient_id) REFERENCES INGREDIENTS (id)
    ON DELETE CASCADE
);