CREATE TABLE USERS
(
  id            INT                NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  username      VARCHAR(50) UNIQUE NOT NULL,
  firstname     VARCHAR(50),
  lastname      VARCHAR(50),
  password      VARCHAR(32),
  magnetic_card VARCHAR(32) UNIQUE,
  is_admin      CHAR(1)                     DEFAULT 'N',
  CONSTRAINT USERS_key PRIMARY KEY (id)
);

CREATE TABLE COCKTAIL_GROUPS
(
  id   INT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  name VARCHAR(50) UNIQUE,
  CONSTRAINT COCKTAIL_GROUPS_key PRIMARY KEY (id)
);

CREATE TABLE COCKTAILS
(
  id       INT         NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  name     VARCHAR(50) NOT NULL,
  group_id INT         NOT NULL,
  CONSTRAINT COCKTAILS_key PRIMARY KEY (id),
  CONSTRAINT COCKTAILS_COCKTAIL_GROUPS_ID_fk
  FOREIGN KEY (group_id) REFERENCES COCKTAIL_GROUPS (id)
    ON DELETE CASCADE
);

CREATE TABLE INGREDIENTS
(
  id       INT                NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  name     VARCHAR(50) UNIQUE NOT NULL,
  velocity DOUBLE             NOT NULL,
  CONSTRAINT INGREDIENTS_key PRIMARY KEY (id)
);

CREATE TABLE COCKTAILS_INGREDIENTS
(
  id            INT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  cocktail_id   INT NOT NULL,
  ingredient_id INT NOT NULL,
  millilitres   INT NOT NULL,
  CONSTRAINT COCKTAILS_INGREDIENTS_key PRIMARY KEY (id),
  CONSTRAINT COCKTAILS_INGREDIENTS_COCKTAIL_fk
  FOREIGN KEY (cocktail_id) REFERENCES COCKTAILS (id)
    ON DELETE CASCADE,
  CONSTRAINT COCKTAILS_INGREDIENTS_INGREDIENTS_fk
  FOREIGN KEY (ingredient_id) REFERENCES INGREDIENTS (id)
    ON DELETE CASCADE
);

CREATE TABLE PUMPS
(
  id            INT  NOT NULL,
  pin_ground    INT  NOT NULL,
  pin_in        INT  NOT NULL,
  ingredient_id INT,
  enabled       CHAR NOT NULL DEFAULT 'N',
  CONSTRAINT PUMPS_key PRIMARY KEY (id),
  CONSTRAINT PUMPS_INGREDIENTS_fk
  FOREIGN KEY (ingredient_id) REFERENCES INGREDIENTS (id)
);

CREATE TABLE HISTORY_LOG
(
  id         INT          NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  type       INT          NOT NULL,
  messgage   VARCHAR(255) NOT NULL,
  username   VARCHAR(50),
  event_date DATE                  DEFAULT current date,
  CONSTRAINT HISTORY_LOG_key PRIMARY KEY (id)
);